// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Promise = require("./Promise.bs.js");

$$Promise.map($$Promise.asyncSequence5((function (param) {
            return $$Promise.resolve(1);
          }), (function (arg) {
            return $$Promise.resolve(arg.a + 2 | 0);
          }), (function (param) {
            return $$Promise.resolve(3);
          }), (function (param) {
            return $$Promise.resolve(4);
          }), (function (arg) {
            return $$Promise.resolve((arg.a + arg.c | 0) + 3 | 0);
          })), (function (prim) {
        console.log(prim);
        
      }));

/*  Not a pure module */
