// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function resolve(prim) {
  return Promise.resolve(prim);
}

function $$catch(a, f) {
  return a.catch(Curry.__1(f));
}

function map(a, fn) {
  return a.then(function (v) {
              return Promise.resolve(Curry._1(fn, v));
            });
}

function flatMap(a, fn) {
  return a.then(Curry.__1(fn));
}

function catchResolve(a, fn) {
  return a.catch(function (e) {
              return Promise.resolve(Curry._1(fn, e));
            });
}

function asyncSequence(a, b) {
  var a$1 = map(Curry._1(a, undefined), (function (ar) {
          return {
                  a: ar
                };
        }));
  return a$1.then(function (ar) {
              return map(Curry._1(b, ar), (function (br) {
                            return {
                                    a: ar.a,
                                    b: br
                                  };
                          }));
            });
}

function asyncSequence3(a, b, c) {
  var a$1 = asyncSequence(a, b);
  return a$1.then(function (abr) {
              return map(Curry._1(c, abr), (function (cr) {
                            return {
                                    a: abr.a,
                                    b: abr.b,
                                    c: cr
                                  };
                          }));
            });
}

function asyncSequence4(a, b, c, d) {
  var a$1 = asyncSequence3(a, b, c);
  return a$1.then(function (abcr) {
              return map(Curry._1(d, abcr), (function (dr) {
                            return {
                                    a: abcr.a,
                                    b: abcr.b,
                                    c: abcr.c,
                                    d: dr
                                  };
                          }));
            });
}

function asyncSequence5(a, b, c, d, e) {
  var a$1 = asyncSequence4(a, b, c, d);
  return a$1.then(function (abcdr) {
              return map(Curry._1(e, abcdr), (function (er) {
                            return {
                                    a: abcdr.a,
                                    b: abcdr.b,
                                    c: abcdr.c,
                                    d: abcdr.d,
                                    e: er
                                  };
                          }));
            });
}

function asyncSequence6(a, b, c, d, e, f) {
  var a$1 = asyncSequence5(a, b, c, d, e);
  return a$1.then(function (abcder) {
              return map(Curry._1(f, abcder), (function (fr) {
                            return {
                                    a: abcder.a,
                                    b: abcder.b,
                                    c: abcder.c,
                                    d: abcder.d,
                                    e: abcder.e,
                                    f: fr
                                  };
                          }));
            });
}

function asyncSequence7(a, b, c, d, e, f, g) {
  var a$1 = asyncSequence6(a, b, c, d, e, f);
  return a$1.then(function (abcdefr) {
              return map(Curry._1(g, abcdefr), (function (gr) {
                            return {
                                    a: abcdefr.a,
                                    b: abcdefr.b,
                                    c: abcdefr.c,
                                    d: abcdefr.d,
                                    e: abcdefr.e,
                                    f: abcdefr.f,
                                    g: gr
                                  };
                          }));
            });
}

var thenResolve = map;

var $$then = flatMap;

exports.resolve = resolve;
exports.$$catch = $$catch;
exports.map = map;
exports.flatMap = flatMap;
exports.catchResolve = catchResolve;
exports.thenResolve = thenResolve;
exports.$$then = $$then;
exports.asyncSequence = asyncSequence;
exports.asyncSequence3 = asyncSequence3;
exports.asyncSequence4 = asyncSequence4;
exports.asyncSequence5 = asyncSequence5;
exports.asyncSequence6 = asyncSequence6;
exports.asyncSequence7 = asyncSequence7;
/* No side effect */
